Psql15
ome/ansible-role-postgresql-client pull request #9
Opened 2023-11-09 21:41 UTC by jburel

This PR
* fixes warning and error
* adds support for psql 15
* removes psql 11 and 9.6

2024-02-21 14:18 UTC, jburel commented
I will need to rebase this PR first

2024-02-21 14:26 UTC, pwalczysko commented
Maybe problems with syntax during rebase ?
![Screenshot 2024-02-21 at 14 26 12](https://github.com/ome/ansible-role-postgresql-client/assets/2478303/56f4b52f-2360-41cc-87e3-7b4bb7f0c5d6)

2024-02-21 15:35 UTC, pwalczysko requested changes
There are some remnants of a rebase I believe 

``<<<<<<< HEAD`` in the redhat.yml file

The test is failing accordingly

2024-02-21 17:07 UTC, jburel commented
I forgot to save the file!!

2024-02-22 15:43 UTC, pwalczysko commented on meta/main.yml
> +  min_ansible_version: '2.6'
2.10 as discussed ?
similarly to
https://github.com/ome/ansible-role-fluentd/blob/d1a5c0e19bdccdb0c8ae17f44c8f136bb449477e/meta/main.yml#L7 - according

2024-02-22 15:45 UTC, pwalczysko commented on vars/main.yml
> +    setup: postgresql-15-setup
missing "16" ?

2024-02-22 15:46 UTC, pwalczysko requested changes
Two issues
- minimal ansible version should be 2.10
- a "16" block is missing in ``vars/main.yml``

2024-02-23 11:34 UTC, pwalczysko approved these changes

2024-03-04 09:23 UTC, merged